package persistence.entities;
// Generated 31 mars 2021 à 14:24:16 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TEtudiant generated by hbm2java
 */
@Entity
@Table(name = "T_ETUDIANT", schema = "TPETUDIANT")
public class TEtudiant implements java.io.Serializable {

	private BigDecimal ECode;
	private String ENom;
	private Double EMoyenne;

	public TEtudiant() {
	}

	public TEtudiant(BigDecimal ECode) {
		this.ECode = ECode;
	}

	public TEtudiant(BigDecimal ECode, String ENom, Double EMoyenne) {
		this.ECode = ECode;
		this.ENom = ENom;
		this.EMoyenne = EMoyenne;
	}

	@Id

	@Column(name = "E_CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getECode() {
		return this.ECode;
	}

	public void setECode(BigDecimal ECode) {
		this.ECode = ECode;
	}

	@Column(name = "E_NOM", length = 20)
	public String getENom() {
		return this.ENom;
	}

	public void setENom(String ENom) {
		this.ENom = ENom;
	}

	@Column(name = "E_MOYENNE", precision = 126, scale = 0)
	public Double getEMoyenne() {
		return this.EMoyenne;
	}

	public void setEMoyenne(Double EMoyenne) {
		this.EMoyenne = EMoyenne;
	}

}
